import type { Metadata } from "next";
import TopNavbar from "./Component/Navbar/page";
import Footer from "./Component/Footer/page";

import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-multi-carousel/lib/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
